#version: "3.8" //they no longer need to declear the version in the new docker compose
services:
  api:
    #build: . #removed build for production as we will use a prebuilt image, when we build image in development, we puch to dockerhub then in production we pull from there
    image: stephanek1993/fastapi:1 #the image we pushed to docker hub after building it locally
    depends_on: #means we wamt the postgres to start first before api, api depends on postgres
      - postgres
    ports:
      - "80:8000" #changed to port 80 for production
    #env_file: can be used  too instead of listing the environment variables one by one like below
    #  - ./.env #yes this method works with the line above
    #volumes: //removed for production as we dont want live code updates in production
    #  - ./:/usr/src/app:ro  #mounting the current directory to the /app directory in the container so any changes we make locally reflect in the container
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 #--reload removed for production
    environment:   
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} #using environment variables for production instead of hardcoding them, "${}" syntax to reference environment variables
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:  #no build bc we are using an existing image from docker hub which is advised for databases
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data #path inside the container where the data we want to store on our local machine incase the container stops is located
volumes:
  postgres_db: #named volume for persisting the database data, defined as a global volume outside the postgress so other containers can reference this data
    